
name: Gemini CLI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-gemini-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Gemini CLI
        uses: google-github-actions/run-gemini-cli@v1
        with:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # Add any other arguments you want to pass to the Gemini CLI here
          # For example: args: "lint --fix"
